version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: docker-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  mongo:
    image: mongo:latest
    container_name: docker-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db

  redis:
    image: redis:latest
    container_name: docker-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

  neo4j:
    image: neo4j:latest
    container_name: docker-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/logs:/logs 
      - ./neo4j/conf:/var/lib/neo4j/conf 
      - ./neo4j/import:/var/lib/neo4j/import 
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/neo4j