version: "3.7"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      - ./mysql/sql:/tmp/sql
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
