version: '3.7'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/logs:/logs 
      - ./neo4j/conf:/var/lib/neo4j/conf 
      - ./neo4j/import:/var/lib/neo4j/import 
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/techial
